-- Event management: admin-editable events, safe public view, storage for
-- artwork, and a race-safe reservation function.

-- 1. New event columns (all additive; existing rows keep working).
alter table public.events
  add column if not exists subtitle text not null default '',
  add column if not exists logo_url text,
  add column if not exists ends_at timestamptz,
  add column if not exists rsvp_opens_at timestamptz,
  add column if not exists rsvp_closes_at timestamptz,
  add column if not exists max_tickets_per_rsvp integer not null default 4,
  add column if not exists admin_notes text not null default '',
  add column if not exists ticket_type text not null default 'free',
  add column if not exists price_cents integer not null default 0;

alter table public.events drop constraint if exists events_max_tickets_per_rsvp_check;
alter table public.events add constraint events_max_tickets_per_rsvp_check
  check (max_tickets_per_rsvp between 1 and 10);
alter table public.events drop constraint if exists events_ticket_type_check;
alter table public.events add constraint events_ticket_type_check
  check (ticket_type in ('free', 'paid'));
alter table public.events drop constraint if exists events_price_cents_check;
alter table public.events add constraint events_price_cents_check
  check (price_cents >= 0);

-- Allow a cancelled state (blocks RSVPs automatically: the RSVP API requires
-- status = 'published', and the public view only exposes published/archived).
alter table public.events drop constraint if exists events_status_check;
alter table public.events add constraint events_status_check
  check (status in ('draft', 'published', 'archived', 'cancelled'));

-- Reservations may now hold up to 10 tickets; the per-event cap is enforced
-- by max_tickets_per_rsvp in the API.
alter table public.reservations drop constraint if exists reservations_quantity_check;
alter table public.reservations add constraint reservations_quantity_check
  check (quantity between 1 and 10);

-- 2. Safe public read model: only published/archived events, only guest-facing
-- columns. admin_notes and other internals never reach the browser.
create or replace view public.public_events
with (security_invoker = off) as
select
  e.id,
  e.slug,
  e.title,
  e.subtitle,
  e.kicker,
  e.description,
  e.poster_url,
  e.logo_url,
  e.starts_at,
  e.ends_at,
  e.doors_at,
  e.gate_closes_at,
  e.capacity_standard,
  e.capacity_overflow,
  e.status,
  e.is_invite_only,
  e.program,
  e.entry_instructions,
  e.accessibility_note,
  e.rsvp_opens_at,
  e.rsvp_closes_at,
  e.max_tickets_per_rsvp,
  v.name as venue_name,
  v.address as venue_address,
  v.neighborhood as venue_neighborhood
from public.events e
left join public.venues v on v.id = e.venue_id
where e.status in ('published', 'archived');

grant select on public.public_events to anon, authenticated;

-- 3. Storage bucket for poster/logo uploads. Public read, admin-only write.
insert into storage.buckets (id, name, public)
values ('event-art', 'event-art', true)
on conflict (id) do nothing;

drop policy if exists "public read event art" on storage.objects;
drop policy if exists "admins insert event art" on storage.objects;
drop policy if exists "admins update event art" on storage.objects;
drop policy if exists "admins delete event art" on storage.objects;

create policy "public read event art" on storage.objects
  for select using (bucket_id = 'event-art');
create policy "admins insert event art" on storage.objects
  for insert to authenticated with check (bucket_id = 'event-art' and public.is_admin());
create policy "admins update event art" on storage.objects
  for update to authenticated using (bucket_id = 'event-art' and public.is_admin());
create policy "admins delete event art" on storage.objects
  for delete to authenticated using (bucket_id = 'event-art' and public.is_admin());

-- 4. Race-safe reservation creation. Locks the event row so two simultaneous
-- RSVPs serialize and cannot oversell the last seat. Token hashes are
-- generated by the API; seat types are decided here, in order.
create or replace function public.create_reservation_atomic(
  event_uuid uuid,
  p_guest_name text,
  p_guest_email text,
  p_quantity integer,
  p_invite_code text,
  p_cancel_token_hash text,
  p_token_hashes text[]
)
returns table (reservation_id uuid, seat_types text[])
language plpgsql
security definer
set search_path = public
as $$
declare
  ev public.events%rowtype;
  taken integer;
  seats text[] := array[]::text[];
  seat text;
  res_id uuid := gen_random_uuid();
  res_status text;
  i integer;
begin
  if p_quantity < 1 or p_quantity > 10 or array_length(p_token_hashes, 1) is distinct from p_quantity then
    raise exception 'invalid quantity';
  end if;

  select * into ev from public.events where id = event_uuid for update;
  if not found or ev.status <> 'published' then
    raise exception 'event not open';
  end if;

  select count(*) into taken from public.tickets
  where event_id = event_uuid and status = 'valid';

  for i in 1..p_quantity loop
    if taken + i - 1 < ev.capacity_standard then
      seat := 'standard';
    elsif taken + i - 1 < ev.capacity_standard + ev.capacity_overflow then
      seat := 'overflow';
    else
      seat := 'waitlist';
    end if;
    seats := seats || seat;
  end loop;

  res_status := case when seats <@ array['waitlist'] then 'waitlisted' else 'confirmed' end;

  insert into public.reservations (id, event_id, guest_name, guest_email, quantity, status, invite_code, cancel_token_hash)
  values (res_id, event_uuid, p_guest_name, p_guest_email, p_quantity, res_status, nullif(p_invite_code, ''), p_cancel_token_hash);

  for i in 1..p_quantity loop
    insert into public.tickets (event_id, reservation_id, token_hash, seat_type, status)
    values (event_uuid, res_id, p_token_hashes[i], seats[i], case when seats[i] = 'waitlist' then 'waitlisted' else 'valid' end);

    if seats[i] = 'waitlist' then
      insert into public.waitlist_entries (event_id, reservation_id, guest_name, guest_email, party_size, position_hint)
      values (event_uuid, res_id, p_guest_name, p_guest_email, p_quantity, taken + i);
    end if;
  end loop;

  return query select res_id, seats;
end;
$$;

grant execute on function public.create_reservation_atomic(uuid, text, text, integer, text, text, text[]) to anon, authenticated;
